### ISSUE TITLE
yadt crashes if yum-plugin-replace is enabled

### ISSUE THREAD

**Issue by Woi** [yadt/yadtshell#24]
Hey,

yadt crashes when used with yum-plugin-replace with the following message:

```
STATUS FAILED
INFO     For details see: "<FILENAME_WITH_FULL_PATH>status.log"
INFO     The first error was:
		20151014-110109 ERROR twisted.py:201 mapping values are not allowed in this context
```

Content of the Logfile *<PATH>/yadtshell-lock.1.stderr*:
```
ERROR    mapping values are not allowed in this context
  in "<byte string>", line 3, column 24
ERROR    errors occured during status
CRITICAL exit code: 1
Traceback (most recent call last):
  File "/usr/bin/yadtshell", line 121, in <module>
    components = yadtshell.util.restore_current_state()
  File "/usr/lib/python2.6/site-packages/yadtshell/util.py", line 95, in restore_current_state
    deserialized_state = restore(current_state())
  File "/usr/lib/python2.6/site-packages/yadtshell/util.py", line 57, in restore
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: '<HOMEDIR_OF_USER>/.yadtshell/<FQDN_OF_MGMT_HOST>/tmp/data/logs/system-updates/20151014-0900/<FG>/current_state.components'
```

Content of the Logfile *<PATH>/yadtshell-lock.0.stdout* on host *<FQDN_OF_MGMT_HOST>*
```
STATUS FAILED
INFO     For details see: "<PATH>.status.log"
INFO     The first error was:
		20151014-110100 ERROR twisted.py:201 mapping values are not allowed in this context
```

Content of the Logfile *<PATH>/yadtshell-lock.0.stderr* on host *<FQDN_HOSTNAME>*
```
ERROR    mapping values are not allowed in this context
  in "<byte string>", line 3, column 24
ERROR    errors occured during status
CRITICAL exit code: 1
Traceback (most recent call last):
  File "/usr/bin/yadtshell", line 121, in <module>
    components = yadtshell.util.restore_current_state()
  File "/usr/lib/python2.6/site-packages/yadtshell/util.py", line 95, in restore_current_state
    deserialized_state = restore(current_state())
  File "/usr/lib/python2.6/site-packages/yadtshell/util.py", line 57, in restore
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: '<PATH>/current_state.components'
```

Content of the Logfile *<PATH>/yadtshell-dump.0.stdout* on host *<FQDN_OF_MGMT_HOST>*
```
INFO     call 'yadtshell status' first
```

Content of the Logfile *<PATH>/yadtshell-dump.0.stderr* on host *<FQDN_OF_MGMT_HOST>*
```
CRITICAL cannot restore the current state
```

Content of the Logfile *<PATH>/yadtshell-status.0.stderr* on host *<FQDN_OF_MGMT_HOST>*
```
ERROR    mapping values are not allowed in this context
  in "<byte string>", line 3, column 24
ERROR    errors occured during status
CRITICAL exit code: 1
```

Content of the Logfile *<PATH>/yadtshell-status.0.stdout* on host *<FQDN_OF_MGMT_HOST>*

```
STATUS FAILED
INFO     For details see: "<PATH>.status.log"
INFO     The first error was:
		20151014-110051 ERROR twisted.py:201 mapping values are not allowed in this context
```

**Comment by mriehl** [comment]
The JSON from the minion is broken which leads a follow-up error where the serialized host status is missing.

Can you post the (anonymized) output of running `yadt-status` on the remote host in a gist?

**Comment by Woi** [comment]
This is triggered by yum-plugin-replace writing to stdout/stderr. While it would be nice to make yadt more resilient for this situations, to us it's not a bug but an enhancement. Further more yum-plugin-replace will be obsoleted by moving to dnf: https://www.mankier.com/8/yum2dnf#Packages_Replacement_Without_Yum_Shell_or_Yum_Swap
